# ==========================================
# BUILD STAGE
# ==========================================

FROM eclipse-temurin:17-jdk-jammy AS build

WORKDIR /app

COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

RUN chmod +x mvnw

COPY src src

RUN ./mvnw clean package -DskipTests


# ==========================================
# RUNTIME STAGE
# ==========================================

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 80

ENTRYPOINT ["sh", "-c", "java -jar app.jar --server.port=${PORT:-80}"]
